site_name: Elektripaigaldiste Projekteerimise Juhend
site_url: https://dmitrig372.github.io/ElektriJuhend/
theme:
  name: material
  palette:
    primary:
      main: "#2E7D32"
    accent:
      main: "#607D8B"
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.sections

nav:
  - Sissejuhatus:
      - "1.1 Juhendi Eesmärk ja Käsitlusala": 1_Sissejuhatus/1.1_Juhendi_Eesmärk_ja_Käsitlusala.md
      - "1.2 Juhendi Kasutamine": 1_Sissejuhatus/1.2_Juhendi_Kasutamine.md
      - "1.3 Terminid ja Määratlused": 1_Sissejuhatus/1.3_Terminid_ja_Määratlused.md
      - "1.4 Normatiivsed Viited": 1_Sissejuhatus/1.4_Normatiivsed_Viited.md
      - "1.5 Vastutus ja Pädevus": 1_Sissejuhatus/1.5_Vastutus_ja_Pädevus.md
  - Projekteerimise põhimõtted: 2_Projekteerimine/index.md
  - Dokumentatsioon: 3_Dokument/index.md
  - Tugevvool:
      - Kaabliteed: 4_Tugevvool/4.4_Kaabliteed.md
  - Nõrkvool:
      - Nõrkvoolu ülevaade: 5_Norkvool/index.md
  - Automaatika:
      - Automaatika ülevaade: 6_Automaatika/index.md
  - BIM: 7_BIM/index.md
  - Kvaliteet: 8_Kvaliteet/index.md
  - Lisad: 9_Lisad/index.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - footnotes

plugins:
  - search

extra_css:
  - stylesheets/extra.css

extra:
  version: "v1.0 – 15.04.2025"
