site_name: Elektripaigaldiste Projekteerimise Juhend
site_url: https://dmitrig372.github.io/ElektriJuhend/
theme:
  name: material
  palette:
    primary:
      main: "#2E7D32"
    accent:
      main: "#607D8B"
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.breadcrumbs
    - navigation.top
    - navigation.tracking

nav:
  - Sissejuhatus: 1_Sissejuhatus/index.md
  - Projekteerimise põhimõtted: 2_Projekteerimine/index.md
  - Dokumentatsioon: 3_Dokument/index.md
  - Tugevvool:
      - Kaabliteed: 4_Tugevvool/4.4_Kaabliteed.md
  - Nõrkvool:
      - Nõrkvoolu ülevaade: 5_Norkvool/index.md
  - Automaatika:
      - Automaatika ülevaade: 6_Automaatika/index.md
  - BIM: 7_BIM/index.md
  - Kvaliteet: 8_Kvaliteet/index.md
  - Lisad: 9_Lisad/index.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - footnotes

plugins:
  - search

extra_css:
  - stylesheets/extra.css

extra:
  version: "v1.0 – 15.04.2025"
