site_name: Elektripaigaldiste Projekteerimise Juhend
site_url: https://dmitrig372.github.io/ElektriJuhend/
repo_url: https://github.com/dmitrig372/ElektriJuhend
repo_name: dmitrig372/ElektriJuhend
edit_uri: edit/main/docs/

theme:
  name: material
  language: et
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary:
        main: "#2E7D32"
      accent:
        main: "#607D8B"
      toggle:
        icon: material/weather-night
        name: Lülita tumedasse režiimi
    - scheme: slate
      primary:
        main: "#2E7D32"
      accent:
        main: "#607D8B"
      toggle:
        icon: material/weather-sunny
        name: Lülita heledasse režiimi
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - navigation.footer
    - navigation.repo

nav:
  - "1. Sissejuhatus":
      - "1.1 Juhendi Eesmärk ja Käsitlusala": 1_Sissejuhatus/1.1_Juhendi_Eesmärk_ja_Käsitlusala.md
      - "1.2 Juhendi Kasutamine": 1_Sissejuhatus/1.2_Juhendi_Kasutamine.md
      - "1.3 Terminid ja Määratlused": 1_Sissejuhatus/1.3_Terminid_ja_Määratlused.md
      - "1.4 Normatiivsed Viited": 1_Sissejuhatus/1.4_Normatiivsed_Viited.md
      - "1.5 Vastutus ja Pädevus": 1_Sissejuhatus/1.5_Vastutus_ja_Pädevus.md
  - "2. Projekteerimise põhimõtted":
      - "2.1 Projek­teerimise Etapid": 2_Projekteerimine/2.1_Projekteerimise_Etapid.md
      - "2.2 Lähteülesanne ja Lähteandmed": 2_Projekteerimine/2.2_Lähteülesanne_ja_Lähteandmed.md
      - "2.3 Koostöö Teiste Osapooltega": 2_Projekteerimine/2.3_Koostöö_Teiste_Osapooltega.md
      - "2.4 Riskianalüüs ja Ohutus Projek­teerimises": 2_Projekteerimine/2.4_Riskianalüüs_ja_Ohutus_Projekteerimises.md
  - "3. Dokumentatsioon":
      - "3.1 Üldnõuded Dokumentatsioonile": 3_Dokument/3.1_Üldnõuded_Dokumentatsioonile.md
      - "3.2 Digitaalne Vormistamine ja Esitamine": 3_Dokument/3.2_Digitaalne_Vormistamine_ja_Esitamine.md
      - "3.3 Dokumentide Struktuur Projektis": 3_Dokument/3.3_Dokumentide_Struktuur_Projektis.md
      - "3.4 Jooniste Vormistamise Nõuded": 3_Dokument/3.4_Jooniste_Vormistamise_Nõuded.md
      - "3.5 Skeemide Vormistamine ja Sisu": 3_Dokument/3.5_Skeemide_Vormistamise_ja_Sisu.md
      - "3.6 Spetsifikatsioonid ja Loetelud": 3_Dokument/3.6_Spetsifikatsioonid_ja_Loetelud.md
      - "3.7 Arvutused": 3_Dokument/3.7_Arvutused.md
  - "4. Tugevvool":
      - Üldskeemid: 4_Tugevvool/4.2_Yldskeemid.md
      - Kilbiskeemid: 4_Tugevvool/4.3_Kilbiskeemid.md
      - Kaabliteed: 4_Tugevvool/4.4_Kaabliteed.md
      - Valgustuspaigaldised: 4_Tugevvool/4.5_Valgustuspaigaldised.md
      - Jõupaigaldised: 4_Tugevvool/4.6_Jõupaigaldis.md
      - Maandus ja piksekaitse: 4_Tugevvool/4.7_Maandus_piksekaitse.md
  - "5. Nõrkvool":
      - "5.1 Ülevaade": 5_Norkvool/5.1_Norkvool.md
      - "5.2 Üldnõuded ja standardid": 5_Norkvool/5.2_Yldnõuded_Standardid.md
      - "5.3 Andmeside": 5_Norkvool/5.3_Andmeside.md
      - "5.4 Sidevõrgud": 5_Norkvool/5.4_Sidevorgud.md
      - "5.5 Antennisüsteemid": 5_Norkvool/5.5_Antennisysteemid.md
      - "5.6 Helindussüsteemid": 5_Norkvool/5.6_Helindussysteemid.md
      - "5.7 Turvasüsteemid": 5_Norkvool/5.7_Turvasüsteemid.md
      - "5.8 ATS": 5_Norkvool/5.8_ATS.md
      - "5.9 Muud": 5_Norkvool/5.9_Muud.md
  - "6. Automaatika":
      - "6.1 Ülevaade": 6_Automaatika/6.1_Automaatika.md
      - "6.2 Üldnõuded ja standardid": 6_Automaatika/6.2_Yldnouded_ja_standardid.md
      - "6.3 Seletuskiri": 6_Automaatika/6.3_Seletuskiri.md
      - "6.4 Struktuurskeemid": 6_Automaatika/6.4_Struktuurskeemid.md
      - "6.5 Tasapinnaplaanid": 6_Automaatika/6.5_Tasapinnaplaanid.md
      - "6.6 Loetelud": 6_Automaatika/6.6_Loetelud.md
      - "6.7 BIM nõuded": 6_Automaatika/6.7_BIM_Nouded.md
  - "7. BIM":
      - "7.1 Üldpõhimõtted ja Terminoloogia": 7_BIM/7.1_Üldpõhimõtted_ja_Terminoloogia.md
      - "7.2 Mudeli Detailsusaste (LOD) Staadiumite Kaupa": 7_BIM/7.2_Mudeli_Detailsusaste_LOD_Staadiumite_Kaupa.md
      - "7.3 Modelleerimise Standardid": 7_BIM/7.3_Modelleerimise_Standardid.md
      - "7.4 Tarkvara ja Failivormingud (IFC jm)": 7_BIM/7.4_Tarkvara_ja_Failivormingud_IFC_jm.md
      - "7.5 Koostöö ja Koordineerimine Mudelis": 7_BIM/7.5_Koostöö_ja_Koordineerimine_Mudelis.md
      - "7.6 Mudelipõhised Väljundid": 7_BIM/7.6_Mudelipõhised_Väljundid.md
  - "8. Kvaliteet":
      - "8.1 Ülevaade": 8_Kvaliteet/index.md
      - "8.2 Kontroll ja Testimine": 8_Kvaliteet/8.2_Kontroll_ja_Testimine.md
      - "8.3 Dokumentatsioon": 8_Kvaliteet/8.3_Dokumentatsioon.md
      - "8.4 Standardid ja Nõuded": 8_Kvaliteet/8.4_Standardid_ja_Nouded.md
  - "9. Lisad":
      - "9.1 Ülevaade": 9_Lisad/index.md
      - "9.2 Viited": 9_Lisad/9.2_Viited.md
      - "9.3 Sõnastik": 9_Lisad/9.3_Sonastik.md
      - "9.4 Näited": 9_Lisad/9.4_Naited.md
      - "9.5 Tabelid": 9_Lisad/9.5_Tabelid.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - footnotes

plugins:
  - search
  - print-site:
      add_to_navigation: true
      print_page_title: "Prindi kogu juhend PDF-iks"

extra_css:
  - stylesheets/extra.css

extra:
  version: "v1.0 – 15.04.2025"
