site_name: Elektripaigaldiste Projekteerimise Juhend
site_url: https://dmitrig372.github.io/ElektriJuhend/
theme:
  name: material
  language: et
  palette:
    - scheme: default
      primary:
        main: "#2E7D32"
      accent:
        main: "#607D8B"
      toggle:
        icon: material/weather-night
        name: Lülita tumedasse režiimi
    - scheme: slate
      primary:
        main: "#2E7D32"
      accent:
        main: "#607D8B"
      toggle:
        icon: material/weather-sunny
        name: Lülita heledasse režiimi
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.sections

nav:
  - "1. Sissejuhatus":
      - "1.1 Juhendi Eesmärk ja Käsitlusala": 1_Sissejuhatus/1.1_Juhendi_Eesmärk_ja_Käsitlusala.md
      - "1.2 Juhendi Kasutamine": 1_Sissejuhatus/1.2_Juhendi_Kasutamine.md
      - "1.3 Terminid ja Määratlused": 1_Sissejuhatus/1.3_Terminid_ja_Määratlused.md
      - "1.4 Normatiivsed Viited": 1_Sissejuhatus/1.4_Normatiivsed_Viited.md
      - "1.5 Vastutus ja Pädevus": 1_Sissejuhatus/1.5_Vastutus_ja_Pädevus.md
  - "2. Projekteerimise põhimõtted":
      - "2.1 Projek­teerimise Etapid": 2_Projekteerimine/2.1_Projekteerimise_Etapid.md
      - "2.2 Lähteülesanne ja Lähteandmed": 2_Projekteerimine/2.2_Lähteülesanne_ja_Lähteandmed.md
      - "2.3 Koostöö Teiste Osapooltega": 2_Projekteerimine/2.3_Koostöö_Teiste_Osapooltega.md
      - "2.4 Riskianalüüs ja Ohutus Projek­teerimises": 2_Projekteerimine/2.4_Riskianalüüs_ja_Ohutus_Projekteerimises.md
  - "3. Dokumentatsioon":
      - "3.1 Üldnõuded Dokumentatsioonile": 3_Dokument/3.1_Üldnõuded_Dokumentatsioonile.md
      - "3.2 Digitaalne Vormistamine ja Esitamine": 3_Dokument/3.2_Digitaalne_Vormistamine_ja_Esitamine.md
      - "3.3 Dokumentide Struktuur Projektis": 3_Dokument/3.3_Dokumentide_Struktuur_Projektis.md
      - "3.4 Jooniste Vormistamise Nõuded": 3_Dokument/3.4_Jooniste_Vormistamise_Nõuded.md
      - "3.5 Skeemide Vormistamine ja Sisu": 3_Dokument/3.5_Skeemide_Vormistamise_ja_Sisu.md
      - "3.6 Spetsifikatsioonid ja Loetelud": 3_Dokument/3.6_Spetsifikatsioonid_ja_Loetelud.md
      - "3.7 Arvutused": 3_Dokument/3.7_Arvutused.md
  - "4. Tugevvool":
      - Kaabliteed: 4_Tugevvool/4.4_Kaabliteed.md
      - Valgustuspaigaldised: 4_Tugevvool/4.5_Valgustuspaigaldised.md
  - "5. Nõrkvool":
      - Nõrkvoolu ülevaade: 5_Norkvool/index.md
  - "6. Automaatika":
      - Automaatika ülevaade: 6_Automaatika/index.md
  - "7. BIM":
      - "7.1 Üldpõhimõtted ja Terminoloogia": 7_BIM/7.1_Üldpõhimõtted_ja_Terminoloogia.md
      - "7.2 Mudeli Detailsusaste (LOD) Staadiumite Kaupa": 7_BIM/7.2_Mudeli_Detailsusaste_LOD_Staadiumite_Kaupa.md
      - "7.3 Modelleerimise Standardid": 7_BIM/7.3_Modelleerimise_Standardid.md
      - "7.4 Tarkvara ja Failivormingud (IFC jm)": 7_BIM/7.4_Tarkvara_ja_Failivormingud_IFC_jm.md
      - "7.5 Koostöö ja Koordineerimine Mudelis": 7_BIM/7.5_Koostöö_ja_Koordineerimine_Mudelis.md
      - "7.6 Mudelipõhised Väljundid": 7_BIM/7.6_Mudelipõhised_Väljundid.md
  - "8. Kvaliteet": 8_Kvaliteet/index.md
  - "9. Lisad": 9_Lisad/index.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - footnotes

plugins:
  - search

extra_css:
  - stylesheets/extra.css

extra:
  version: "v1.0 – 15.04.2025"
